### PR TITLE
Cleanup Makefile

### PR DESCRIPTION
**Pull request by dannbuckley**
I optimized the build for the unix systems and removed "system_platform" since it wasn't being used by anything.

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
We should get rid of # Generic ARM (armv)

**Comment by sergiobenrocha2** [comment]
Is HAVE_NEON used somewhere? We have a lot of garbage in these makefiles from Ctrl+C & Ctrl+V from another makefiles

**Comment by dannbuckley** [comment]
I removed the Generic ARM build stuff. As for HAVE_NEON, I do not know because I am not familiar with the source code for this project.

**Comment by sergiobenrocha2** [comment]
grep -r "HAVE_NEON"

I can find it only in the Makefile, it's not being used.

**Comment by sergiobenrocha2** [comment]
You removed EXE_EXT=.exe, makefile needs it in some places. Put it after line 8

**Comment by sergiobenrocha2** [comment]
Are you sure "make platform=rpi3" will work? You need a:

```ifneq (,$(findstring unix,$(platform)))```

in line 37. Take a look again in the changes I did in the other makefiles.

**Comment by dannbuckley** [comment]
Ok, the latest commit should fix things. (Sorry, I'm not that experienced with Makefile)

**Comment by sergiobenrocha2** [comment]
Why did you removed this?

```
else ifneq (,$(findstring armv,$(platform)))
   override platform += unix
```

Several packages/scripts use "make platform=armv" yet, you'll broke them without that.

**Comment by sergiobenrocha2** [comment]
Test all the "make platform=xxx" you changed, make sure they are working.

**Comment by dannbuckley** [comment]
I have confirmed that all of the areas that I altered build without error.

**Comment by dannbuckley** [comment]
@twinaphex Can you merge this with the master branch?

**Comment by inactive123** [comment]
Which master branch? You mean merging this PR or something else?

**Comment by dannbuckley** [comment]
I mean merging this PR.

**Comment by inactive123** [comment]
@sergiobenrocha2 Tell me if this is ready to be merged and I'll do it.

**Comment by sergiobenrocha2** [comment]
Yeah I think so

**Pull request merged**
