### PR TITLE
Add Raspberry Pi 3 to Makefile

### PR DESCRIPTION
**Pull request by dannbuckley**

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
We should stop doing this... it's not like rpi3 is a entire new platform.

See: https://github.com/libretro/Genesis-Plus-GX/blob/master/Makefile.libretro#L37

**Comment by sergiobenrocha2** [comment]
And this: https://github.com/libretro/Genesis-Plus-GX/commit/307c6f5c053988af57809e2061c84372803d9be4

**Comment by sergiobenrocha2** [comment]
And this too: https://github.com/libretro/beetle-pce-fast-libretro/commit/1d4c2718c584b4988d516f7d8f82863906477833

**Comment by dannbuckley** [comment]
So... I should just close this then?

**Comment by sergiobenrocha2** [comment]
Yeah. You could help in the Makefiles cleanups

**Comment by dannbuckley** [comment]
Okay, I'll start a new fork and help with that :smile:

**Pull request closed without merging**
