### PR TITLE
Backport Radius' save bios settings

### PR DESCRIPTION
**Pull request by SuperrSonic**
Tested on Wii.

Saves to root, I can't seem to change that via RGUI, either way I would change it in the code to "sd:/retroarch/system/%s%c%s.fs" but I don't think that's my call.

### CODE REVIEW

**Comment by andres-asm** [comment]
No, that would be bad.
Do you have a save directory set?

**Comment by SuperrSonic** [comment]
Save file directory? Yes, I do.

**Comment by inactive123** [comment]
@fr500 Is this safe to merge or not?

**Comment by andres-asm** [comment]
not sure I haven't used the split cores it works fine in the newer core though

**Comment by inactive123** [comment]
Guess we'll take a risk by merging this then. People on Wii/Vita will be able to tell us soon enough if it's bad or not.

**Pull request merged**
