### PR TITLE
Wii: Add Virtual Memory.

### PR DESCRIPTION
**Pull request by Wiimpathy**
The Wii has very limited RAM. This allows loading the biggest games.

It uses the Wii NAND flash as virtual memory. The games also have to be converted/decrypted first to cache files with a PC program called romcnv.
This program is a modified version of romcnv used for MVS2PSP.
Romcnv binaries: http://www.mediafire.com/file/xb783jd9mxhgbos/romcnv_R2.zip
Romcnv Source: http://www.mediafire.com/file/14a55bohl5u1suo/romcnv_src.zip

Note that a few roms(svcpcb for example) are still too large with this method.
With the latest Retroarch(the first tests was 1.3.6), translation support must be
removed(HAVE_LANGEXTRA) in order to load kof2003 and other games.

### CODE REVIEW

**Comment by inactive123** [comment]
Awesome, thanks for contributing this!

**Comment by inactive123** [comment]
Yeah, we could probably exclude HAVE_LANGEXTRA for the Wii build, I sincerely doubt that the people on the Wii need all the extra translations, and this is a platform where there is a lack of RAM, so it would be justifiable to exclude this.

**Comment by Wiimpathy** [comment]
@twinaphex
Maybe just for this core?
In fact, translations are broken for Wii now. Accents and special characters aren't displayed correctly. It happened after this commit : https://github.com/libretro/RetroArch/commit/ebc9ee192b20a4f118ac771498f3c2871dea0141
Non latin(chinese etc) aren't displayed at all. But I don't know exactly when it started.

**Comment by inactive123** [comment]
I don't think it would be wise to selectively disable it for one core alone, and that would get messy pretty quickly.

I will ask @bparker06 if there is any truth to what you pointed out or whether this is a misunderstanding. As far as I am aware, RGUI has never shown special accented characters, or non-western characters, so there cannot have been a regression in this regard.

**Comment by Wiimpathy** [comment]
Ok, you may be right.

Regarding the accents(in french, spanish etc.), I can assure you it was working before, at least for the Wii.
I tried to revert the above commit and the accents are there. But not special characters like 'œ' for example.
I don't remember about non western languages though.

**Pull request merged**
