### PR TITLE
As a standalone NeoGeo core, it should get more attention.

### PR DESCRIPTION
**Pull request by SumavisionQ5**
Add all pre-decrypted ROMsets from latest FBAS.
It will be very helpful for poor performance platforms such as Wii, 3DS.
It will shorten the loading time a lot and reduce the RAM demanded.

### CODE REVIEW

**Comment by Wiimpathy** [comment]
I don't know about 3DS but it won't really change for the Wii. The max size that used to fit in Ram is(was?) Sengoku 3, 48MB. All other larger games use a cache system thanks to the nand memory. See #26

**Comment by ji125443** [comment]
Is it okay to add support to (kof10thd.zip)?

**Comment by SumavisionQ5** [comment]
Ported "insert coin" fix from latest FBN.

**Comment by SumavisionQ5** [comment]
> I don't know about 3DS but it won't really change for the Wii. The max size that used to fit in Ram is(was?) Sengoku 3, 48MB. All other larger games use a cache system thanks to the nand memory. See #26

Another advantage for adding them is to reduce the ROM size to almost half when you use decrypted ROM sets.

**Comment by Wiimpathy** [comment]
As it is now, it won't work for the Wii. The decrypting part is already skipped for those games. It's done with the Rom converter app. The romcnv app must be modified with the drivers you've added too.
Moreover, I can't see a difference in size between svc and svcd for example. They're both around 88MB.

In fact, it could take a few extra crucial bytes for nothing. Like the pcb versions of some games that are much too large for this platform, they should be excluded since they won't run anyway.

**Comment by SumavisionQ5** [comment]
> As it is now, it won't work for the Wii. The decrypting part is already skipped for those games. It's done with the Rom converter app. The romcnv app must be modified with the drivers you've added too.
> Moreover, I can't see a difference in size between svc and svcd for example. They're both around 88MB.
> 
> In fact, it could take a few extra crucial bytes for nothing. Like the pcb versions of some games that are much too large for this platform, they should be excluded since they won't run anyway.

For nothing? I don't think so. Wii is too old, and It does not deserve a new version. People can use old version instead. But for platforms such as RPi,  I added those decrypted ROM sets and the sizes of zip files can be greatly reduced with decrypted C-ROMs. The size I mentioned here is not RAM size but storage size on SD card. For Wii, because you decrypted with a program and there is no difference.
If you dont like it, I will just close this PR. Anyway, they will stay on my fork.

**Comment by Wiimpathy** [comment]
Ok, since you're talking of RPI and storage now, so yes you're right. Don't take it wrong, I'm just saying that for the Wii, it would require extra work for no real benefit for Ram usage and loading times. I was thinking of adding the drivers with conditional #ifdef.
That's a good idea and you do as you want, it's not up to me to decide anyway.

But regarding old platforms and people using old versions, I thought it was one of retroarch's goal, aiming old and new platforms. And specifically this core being an older fba version.

**Pull request closed without merging**
